services:
  python_service:
    build:
      context: ./docker/python
#    tty: true
    working_dir: /app
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_ENV=development
#    command: flask run